#!/bin/bash

set -euo pipefail

INSTALL_USER="${OMARCHY_INSTALL_USER:-${1:-}}"
SOURCE_REPO="$(readlink -f "$(dirname "$0")/..")"

fail() {
  echo "[Omarchy] $1" >&2
  exit 1
}

resolve_target_home() {
  if [[ -n ${OMARCHY_INSTALL_HOME:-} ]]; then
    printf '%s' "$OMARCHY_INSTALL_HOME"
    return 0
  fi

  local entry
  entry=$(getent passwd "$INSTALL_USER" || true)

  if [[ -z $entry ]]; then
    return 1
  fi

  printf '%s' "$(printf '%s\n' "$entry" | cut -d: -f6)"
}

write_env_exports() {
  local output_file="$1"

  {
    printf '%s\n' "# Generated by Calamares post-Asahi handoff"
    printf 'export OMARCHY_USER_NAME=%q\n' "${OMARCHY_USER_NAME:-}"
    printf 'export OMARCHY_USER_EMAIL=%q\n' "${OMARCHY_USER_EMAIL:-}"
    printf 'export OMARCHY_TIMEZONE=%q\n' "${OMARCHY_TIMEZONE:-}"
    printf 'export OMARCHY_HOSTNAME=%q\n' "${OMARCHY_HOSTNAME:-}"
    printf 'export OMARCHY_OPTIONAL_PACKAGES=%q\n' "${OMARCHY_OPTIONAL_PACKAGES:-}"
  } >"$output_file"
}

if [[ -z $INSTALL_USER ]]; then
  fail "Set OMARCHY_INSTALL_USER or pass the username as the first argument"
fi

TARGET_HOME="$(resolve_target_home)"

if [[ -z $TARGET_HOME ]]; then
  fail "Could not determine home directory for $INSTALL_USER"
fi

TARGET_REPO="$TARGET_HOME/.local/share/omarchy"
TARGET_ENV_FILE="$TARGET_REPO/calamares/omarchy-install.env"

install -d -m 755 "$TARGET_HOME/.local/share"

if [[ $SOURCE_REPO != "$TARGET_REPO" ]]; then
  if [[ -e $TARGET_REPO && ! -d $TARGET_REPO/.git ]]; then
    fail "$TARGET_REPO exists but is not an Omarchy git checkout"
  fi

  if [[ ! -d $TARGET_REPO/.git ]]; then
    cp -R "$SOURCE_REPO" "$TARGET_REPO"
  fi
fi

install -d -m 755 "$TARGET_REPO/calamares"
write_env_exports "$TARGET_ENV_FILE"
chown -R "$INSTALL_USER:$INSTALL_USER" "$TARGET_HOME/.local"

rm -f /var/tmp/omarchy-install-completed
OMARCHY_INSTALL_USER="$INSTALL_USER" bash "$TARGET_REPO/install/preflight/passwordless-installer.sh"

su - "$INSTALL_USER" -c "bash '$TARGET_REPO/install-calamares.sh' '$TARGET_ENV_FILE'"

if [[ ! -f /var/tmp/omarchy-install-completed ]]; then
  fail "Omarchy installer did not finish cleanly"
fi

echo "[Omarchy] Post-Asahi setup completed for $INSTALL_USER"
