modules-search: [ local ]

instances:
  - id: omarchy_post_asahi_users
    module: users
    config: users-post-asahi.conf
  - id: omarchy_post_asahi_handoff
    module: shellprocess
    config: shellprocess-omarchy-post-asahi.conf

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - users@omarchy_post_asahi_users
      - summary
  - exec:
      - locale
      - keyboard
      - localecfg
      - users@omarchy_post_asahi_users
      - shellprocess@omarchy_post_asahi_handoff
  - show:
      - finished

branding: default
prompt-install: false
dont-chroot: true
oem-setup: true
disable-cancel: false
disable-cancel-during-exec: true
hide-back-and-next-during-exec: true
quit-at-end: false
