defaultGroups:
  - name: wheel
    must_exist: false
    system: true

sudoersGroup: wheel
autologinGroup: autologin
sudoersConfigureWithGroup: true
setRootPassword: false
displayAutologin: true
doAutologin: true

passwordRequirements:
  minLength: 1

allowWeakPasswords: true
allowWeakPasswordsDefault: true

user:
  shell: /bin/bash
  forbidden_names: [ root ]
  home_permissions: "o700"

hostname:
  location: Hostnamed
  writeHostsFile: true
  template: "omarchy-mac"
  forbidden_names: [ localhost ]
