# Themed hyprlock variables, generated by omarchy-theme-set-templates from the
# active theme's colors.toml and `source`d by ~/.config/hypr/hyprlock.conf.
#
# The Mac fork locks at boot with hyprlock (omarchy-mac-lock-on-boot), but
# quattro no longer ships a per-theme hyprlock.conf, so the boot lock rendered
# with hyprlock's bare white defaults. Regenerating this file per theme restores
# a branded, theme-matched lock. rgba(...) alpha (cc ~= 0.8) lets the blurred
# wallpaper show through the input card.
$color       = rgb({{ background_strip }})
$inner_color = rgba({{ background_strip }}cc)
$outer_color = rgb({{ accent_strip }})
$font_color  = rgb({{ foreground_strip }})
$check_color = rgb({{ accent_strip }})
