# Only display the OSD on the currently focused monitor
# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, pamixer --increase 5
bindel = ,XF86AudioLowerVolume, exec, pamixer --decrease 5
bindel = ,XF86AudioMute, exec, pamixer --toggle-mute
bindel = ,XF86AudioMicMute, exec, pamixer --toggle-mute --source 1
bindel = ,XF86MonBrightnessUp, exec, brightnessctl set +5%
bindel = ,XF86MonBrightnessDown, exec, brightnessctl set 5%-

# Keyboard backlight control
bindel = , XF86KbdBrightnessUp, exec, brightness=$(cat /sys/class/leds/kbd_backlight/brightness); new_brightness=$((brightness + 10)); if [ $new_brightness -gt 255 ]; then new_brightness=255; fi; echo $new_brightness | sudo tee /sys/class/leds/kbd_backlight/brightness
bindel = , XF86KbdBrightnessDown, exec, brightness=$(cat /sys/class/leds/kbd_backlight/brightness); new_brightness=$((brightness - 10)); if [ $new_brightness -lt 0 ]; then new_brightness=0; fi; echo $new_brightness | sudo tee /sys/class/leds/kbd_backlight/brightness

# Requires playerctl
bindl = , XF86AudioNext, exec, $osdclient --playerctl next
bindl = , XF86AudioPause, exec, $osdclient --playerctl play-pause
bindl = , XF86AudioPlay, exec, $osdclient --playerctl play-pause
bindl = , XF86AudioPrev, exec, $osdclient --playerctl previous
